import "./globals.css";

export const metadata = {
  title: "Trello CLONE",
  description: "Generated by Ahmed Elfadel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-graybg">{children}</body>
    </html>
  );
}
